### ISSUE TITLE
Is it possible to run composer install in a subdirectory?

### ISSUE THREAD

**Issue by kapoko** [MilesChou/composer-action#2]
In my repo I have my `composer.json` not in the root but in another subdirectory in the repo. Is it possible to specify a working directory with this package, or cd into that directory first?

**Comment by kapoko** [comment]
For anyone wondering, just found out by reading the starter workflows that on ubuntu latest composer just works. 

From: https://github.com/actions/starter-workflows/blob/master/ci/php.yml

```yaml
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: |
        cd ./path/to/composer-app
        composer install --prefer-dist --no-progress --no-suggest
```
