### ISSUE TITLE
git was not found, check that it is installed and in your PATH env.

### ISSUE THREAD

**Issue by Luc45** [MilesChou/composer-action#3]
Hi,

I'm getting an error when trying to run composer install:

```
    Now trying to download from dist
  - Installing phpunit/phpunit (8.5.x-dev 8474e22): Loading from cache
  - Installing codeception/phpunit-wrapper (8.1.2): Loading from cache
  - Installing codeception/stub (3.6.1): Loading from cache
  - Installing composer/ca-bundle (dev-master 95c63ab): Cloning 95c63ab211
    Failed to download composer/ca-bundle from source: Failed to clone https://github.com/composer/ca-bundle.git, git was not found, check that it is installed and in your PATH env.
```

This is what the step looks like:

```yml
- uses: MilesChou/composer-action@master
  with:
    args: install --ignore-platform-reqs
```

Have you ever faced this before, is there something you'd recommend me trying?

Thanks!

**Comment by Luc45** [comment]
This is my whole action, by the way:

```yml
name: Run PHPCS on pull requests

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls

      - uses: MilesChou/composer-action@master
        with:
          args: install --ignore-platform-reqs

      - run: ls
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
      - run: ls

```
