### ISSUE TITLE
PHP version is inaccurate

### ISSUE THREAD

**Issue by samihsoylu** [MilesChou/composer-action#9]
Hi @MilesChou 

Actions in `MilesChou/composer-action/` do not check what PHP version is available while running the "composer --help" command within the testing workflow. Revealing with `php -v` would add certainty that it is the expected PHP version.

I say this, because I recently I encountered this
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/7690781/146270977-b4f7bc75-d023-425c-87d2-b406fcecd4cd.png">

That the docker container PHP version appears to be 8.1 🤔 

Do you see something wrong in my workflow file? This issue did not exist before.
```yml
name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build74:
    name: PHP 7.4 Code quality check
    runs-on: ubuntu-latest
    steps:
      - uses: MilesChou/composer-action/7.4@master
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --no-interaction --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check for PHP syntax errors
        run: ./vendor/bin/parallel-lint --exclude vendor/ .

      - name: Validate PHP code style
        run: ./vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no .
```

Thank you

**Comment by MilesChou** [comment]
Try this config

```yaml
name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build74:
    name: PHP 7.4 Code quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action/7.4@master
        with:
          arg: validate --no-interaction --strict

      - name: Install dependencies
        uses: MilesChou/composer-action/7.4@master
        with:
          arg: install --prefer-dist --no-progress --no-suggest

      - name: Check for PHP syntax errors
        run: ./vendor/bin/parallel-lint --exclude vendor/ .

      - name: Validate PHP code style
        run: ./vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no .
```
